### ISSUE TITLE
Moderators Manager

### ISSUE THREAD

**Issue by andiamine** [JoomBoost/JoomCCK#11]

**Comment by Giorgi625** [comment]
I had problems with selecting moderators on older version of Cobalt, because code for modal windows which was shown to select users as moderators was in core files and it was for Bootstrap 2 and when I used Bootstrap 4 templates, this modal was not working properly. 
I am sure I will not have problem with new version because now both templates and JoomCCK will be BS5 but for some users who do not use BS5 templates, I think will be good if all styling codes will be out of core, so they will be able to edit it with ease in this case. and this way they can fully avoid loading BS5 on their pages if they do not need.

**Comment by andiamine** [comment]
You will not experience the issue, cuz now Joomla 4 support Bootstrap 5. and all Joomla 4 templates support Bootstrap without nay issues.

**Comment by Giorgi625** [comment]
Yes I know this but what about Yootheme templates? I do not use Yootheme templates but they are popular and as I know they do not use BS so will it still need to load BS files to work properly?

**Comment by andiamine** [comment]
Yootheme templates support also Bootstrap 5.

**Comment by andiamine** [comment]
so you will not find any issues using Yootheme templates and Bootstrap templates.

regards,
ANDI
